name: Deploy Infrastructure
run-name: Planning and applying infrastructure changes - ${{ github.actor }}
on:
  workflow_call:
    inputs:
      sha: 
        description: 'Commit sha'
        required: true
        type: 'string'
    # outputs:
    #   greetingMessage: 
    #     description: 'Generated greeting message'
    #     value: ${{ steps.greeting.outputs.message }}

permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout

env:
  TF_VAR_prod_rds_password: ${{ secrets.TF_VAR_prod_rds_password }}
  TF_VAR_prod_backend_secret_key: ${{ secrets.TF_VAR_prod_backend_secret_key }}
  TF_VAR_prod_sendgrid_api_key: ${{ secrets.TF_VAR_prod_sendgrid_api_key }}
  TF_VAR_prod_client_id: ${{ secrets.TF_VAR_prod_client_id }}
  TF_VAR_prod_client_secret: ${{ secrets.TF_VAR_prod_client_secret }}
  TF_VAR_prod_redirect_uri: ${{ secrets.TF_VAR_prod_redirect_uri }}

jobs:
  gather_secrets:
    name: Gather Secrets
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
          aws-region: us-east-2

      - name: Step name
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            TF-VAR-prod*
      - run: printenv

  infrastructure:
      name: Deploy Infrastructure
      runs-on: ubuntu-latest
      needs: gather_secrets
      steps:
      - run: echo ${{ inputs.sha }}
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: ezequielmartell/skipify-aws-infrastructure

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
          aws-region: us-east-2

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Validate
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        id: plan
        run: tofu plan -input=false -no-color
        continue-on-error: true
      
      - name: OpenTofu Apply
        id: apply
        run: tofu apply -auto-approve -no-color