name: Deploy Infrastructure
run-name: Planning and applying infrastructure changes - ${{ github.actor }}
on:
  workflow_call:
    inputs:
      sha: 
        description: 'Commit sha'
        required: true
        type: 'string'
      type:
        description: 'Type of infrastructure to deploy'
        required: true
        type: 'string'
    outputs:
      task_def_arn:
        description: 'Task Definition ARN'
        value: ${{ jobs.infrastructure.outputs.task_def_arn }}

permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout

jobs:
  infrastructure:
      name: Deploy Infrastructure
      runs-on: ubuntu-latest
      outputs:
        task_def_arn: ${{ steps.get_task_def_arn.outputs.task_def_arn }}
      steps:
      - run: echo ${{ inputs.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
          aws-region: us-east-2

      - name: Gather TF-VAR Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            TF-VAR-prod*
      - run: |
          for secret in $(env | grep '^TF_VAR_' | cut -d= -f1); do
            # Extract the part after TF_VAR_ and convert it to lowercase
            suffix=$(echo $secret | sed 's/TF_VAR_//g' | tr '[:upper:]' '[:lower:]')
            # Reconstruct the variable name with TF_VAR in uppercase and the suffix in lowercase
            lower_case_name="TF_VAR_${suffix}"
            value=$(printenv $secret)
            echo "${lower_case_name}=${value}" >> $GITHUB_ENV
          done
        
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: ezequielmartell/skipify-aws-infrastructure

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::637423655132:role/github-actions_role
          aws-region: us-east-2

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Validate
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        id: plan
        run: tofu plan -target="aws_ecs_task_definition.prod_${{ inputs.type }}_web" -var="image_tag=${{ inputs.sha }}" -input=false -no-color
      
      - name: OpenTofu Apply
        id: apply
        run: tofu apply -target="aws_ecs_task_definition.prod_${{ inputs.type }}_web" -var="image_tag=${{ inputs.sha }}" -auto-approve -no-color
      
      - name: Get Task Definition ARN
        id: get_task_def_arn
        run: |
          echo "task_def_arn=$(tofu output -raw task_definition_arn_${{ inputs.type }})"
          echo "task_def_arn=$(tofu output -raw task_definition_arn_${{ inputs.type }})" >> $GITHUB_OUTPUT

        