name: Call Deployment Workflow
run-name: ${{ github.actor }} called deployment workflow
on:
  push:
    branches:
      - main
    
jobs:
  useCallable:
    uses: ./.github/workflows/deploy_infra.yml
    with:
      sha: ${{ github.sha }}