name: Call Deployment Workflow
run-name: ${{ github.actor }} called deployment workflow
on:
  push:
    branches:
      - main

permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout 

jobs:
  depoly_infra:
    name: Trigger Infrastructure Deployment Workflow
    uses: ./.github/workflows/deploy_infra.yml
    with:
      sha: ${{ github.sha }}